; ─── BW16-KIT RTL8720DN — tek hedef — 2.4GHz + 5GHz ─────────────────────────
[platformio]
default_envs = bw16

; ─── BW16-KIT RTL8720DN — birincil hedef — 2.4GHz + 5GHz ────────────────────
[env:bw16]
platform = https://github.com/tmmsunny012/ameba-arduino-d.git#feature-platformio-support
board = rtl8720dn_bw16
framework = arduino

lib_deps =
  EEPROM

lib_ignore =
  WiFiWebServer
  WiFiNINA_Generic
  WiFiNINA
  WiFiEspAT
  WiFiEspAT_STM32

lib_ldf_mode = chain+

build_flags =
  -O2
  -fno-exceptions
  -fno-rtti
  -DBOARD_BW16
  -DCORE_DEBUG_LEVEL=0
monitor_speed = 115200
upload_speed  = 1000000
